### PR TITLE
fix: CI latest-dev-fluvio.yml, workaround cargo bug

### PR DESCRIPTION
**Pull request by digikata**

### CODE REVIEW

**Comment by digikata** [comment]
This fixes the workflow issue #387 

note: cargo remove and add also does not work
```
cargo remove fluvio
cargo add fluvio --git https://github.com/infinyon/fluvio --branch master -F admin
```

**Review by morenol — APPROVED** [review]

**Comment by digikata** [comment]
This lets the intended workflow proceed to test the HEAD of the fluvio branch (which currently will fail due to minor 0.10.15 updates - there is separate patch to fix that).

**Comment by digikata** [comment]
bors retry

**Comment by digikata** [comment]
bors cancel

**Pull request merged**
