### PR TITLE
[Merged by Bors] - chore: bump for 0.14.5 release

### PR DESCRIPTION
**Pull request by digikata**

### CODE REVIEW

**Review by morenol — COMMENTED** [review]
Was 0.14.4 released? I don't see a GitHub release for that one

**Comment by digikata** [comment]
Hmm, I don't see a GH release, but I see a tag and a successfull Release action for v0.14.4

**Review by morenol — APPROVED** [review]

**Comment by morenol** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> Not sure what @fluvio/native... packages are? Are they stil valid?

Not sure about that

**Pull request closed without merging**
